- hosts: localhost
  become: False

  tasks:
    - name: "Set USER_HOME env var facts"
      include_role:
        name: common
        tasks_from: main

    - name: "Decrypt the ansible-vault encrypted files"
      command: ansible-vault decrypt /home/rhmap4-build/rhmap4-build.keytab /home/rhmap4-build/.ssh/id_rsa /home/rhmap4-build/.ssh/id_rsa.pub --vault-password-file /home/rhmap4-build/.password

    - file:
      path: /home/rhmap4-build/.ssh/id_rsa
      owner: rhmap4-build
      group: root
      mode: 0600

    - file:
      path: /home/rhmap4-build/.ssh/id_rsa.pub
      owner: rhmap4-build
      group: root
      mode: 0600

    - name: "Execute kinit"
      command: kinit -kt /home/rhmap4-build/rhmap4-build.keytab rhmap4-build/mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com@REDHAT.COM

    - name: "Set USER_HOME env var facts"
      include_role:
        name: rhmap_productization
        tasks_from: create_productization_directory_structure

    - name: "Set USER_HOME env var facts"
      include_role:
        name: rhmap_productization
        tasks_from: clone_productization_repos


  vars:
    - git_user: "rhmap4-build"
