---
- name: "rhmap-fh-aaa-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-aaa-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-aaa-docker"

- name: "rhmap-fh-appstore-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-appstore-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-appstore-docker"

- name: "rhmap-fh-mbaas-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-mbaas-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-mbaas-docker"

- name: "rhmap-fh-messaging-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-messaging-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-messaging-docker"

- name: "rhmap-fh-metrics-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-metrics-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-metrics-docker"

- name: "rhmap-fh-ngui-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-ngui-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-ngui-docker"

- name: "rhmap-fh-scm-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-scm-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-scm-docker"

- name: "rhmap-fh-statsd-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-statsd-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-statsd-docker"

- name: "rhmap-fh-supercore-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-supercore-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-supercore-docker"

- name: "rhmap-memcached-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-memcached-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-memcached-docker"

- name: "rhmap-mongodb-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-mongodb-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-mongodb-docker"

- name: "rhmap-mysql-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-mysql-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-mysql-docker"

- name: "rhmap-fh-sdks-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-sdks-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-sdks-docker"

- name: "rhmap-httpd-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-httpd-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-httpd-docker"

- name: "rhmap-httpd-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-httpd-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-httpd-docker"

- name: "rhmap-nagios-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-nagios-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-nagios-docker"

- name: "rhmap-millicore-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-millicore-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-millicore-docker"

- name: "rhmap-redis-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-redis-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-redis-docker"

- name: "rhmap-ups-eap-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-ups-eap-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-ups-eap-docker"

- name: "rhmap-gitlab-shell-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-gitlab-shell-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-gitlab-shell-docker"

- name: "rhmap-wildcard-proxy-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-wildcard-proxy-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-wildcard-proxy-docker"

- name: "rhmap-gitlab-migrate-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-gitlab-migrate-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-gitlab-migrate-docker"

- name: "rhmap-installer-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-installer-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-installer-docker"

- name: "rhmap-digger-android-sdk-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-digger-android-sdk-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-digger-android-sdk-docker"

- name: "rhmap-digger-android-slave-docker"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-digger-android-slave-docker"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-digger-android-slave-docker"

- name: "rhmap-fh-system-dump-tool"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-system-dump-tool"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/rhmap-fh-system-dump-tool"

- name: "rhmap-fh-openshift-templates"
  git:
    repo: "ssh://{{username}}@pkgs.devel.redhat.com/rpms/rhmap-fh-openshift-templates"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/rpm/rhmap-fh-openshift-templates"

- name: "rhmap-ansible"
  git:
    repo: "git@github.com:fheng/rhmap-ansible.git"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/docker/upstream/rhmap-ansible"

- name: "mobile-platform-tooling"
  git:
    repo: "ssh://{{username}}@code.engineering.redhat.com/jboss-mobile/mobile-platform-tooling"
    dest: "{{USER_HOME}}/Productization/mobile-platform-tooling"

- name: "fh-core-openshift-templates"
  git:
    repo: "ssh://{{username}}@code.engineering.redhat.com/jboss-mobile/fh-core-openshift-templates"
    dest: "{{USER_HOME}}/Productization/_Product_builds/code-engineering/_Node_JS/fh-core-openshift-templates"
