---
- name: "Create docker directory"
  file:
    path: "{{ USER_HOME }}/Productization/_Product_builds/code-engineering/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "docker/upstream"
    - "rpm"
    - "_Node_JS"